//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BemaxWeekendTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutSetting
    {
        public int Id { get; set; }
        public string Photo { get; set; }
        public string MenuTitle { get; set; }
        public string FooterTitle { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> OpenTime { get; set; }
        public Nullable<System.DateTime> ClosedTime { get; set; }
        public string TwitterContent { get; set; }
        public string Twitterlink { get; set; }
        public Nullable<System.DateTime> TwitterTime { get; set; }
        public string CopyRightContent { get; set; }
    }
}
