//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BemaxWeekendTask.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BemaxEntities2 : DbContext
    {
        public BemaxEntities2()
            : base("name=BemaxEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutFistContent> AboutFistContents { get; set; }
        public virtual DbSet<AboutRemax> AboutRemaxes { get; set; }
        public virtual DbSet<AboutSetting> AboutSettings { get; set; }
        public virtual DbSet<AllBranPhoto> AllBranPhotoes { get; set; }
        public virtual DbSet<ContactSetting> ContactSettings { get; set; }
        public virtual DbSet<IconBox> IconBoxes { get; set; }
        public virtual DbSet<LatestPost> LatestPosts { get; set; }
        public virtual DbSet<MiniSlider> MiniSliders { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<Testimonial> Testimonials { get; set; }
        public virtual DbSet<TestimonialsBody> TestimonialsBodies { get; set; }
        public virtual DbSet<TestimonialsHeader> TestimonialsHeaders { get; set; }
        public virtual DbSet<TheGreatTeamArea> TheGreatTeamAreas { get; set; }
        public virtual DbSet<WeAreBemaxArea> WeAreBemaxAreas { get; set; }
        public virtual DbSet<WhyChooseUsArea> WhyChooseUsAreas { get; set; }
        public virtual DbSet<WorkingWithOutArea> WorkingWithOutAreas { get; set; }
    }
}
