//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BemaxWeekendTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LatestPost
    {
        public int Id { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string PostTitle { get; set; }
        public string PostContent { get; set; }
        public string PostIcon { get; set; }
        public string IconTitle { get; set; }
        public string PostIcon2 { get; set; }
        public string PostTitle2 { get; set; }
    }
}
