//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BemaxWeekendTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public string BrandImage { get; set; }
        public string HeaderListName { get; set; }
        public string FooterContent { get; set; }
        public string Icon { get; set; }
        public string FooterShortTitle { get; set; }
        public string FooterMainTitle { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string SubscribeContent { get; set; }
        public string CopyRightContent { get; set; }
    }
}
