//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BemaxWeekendTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int Id { get; set; }
        public string Photo { get; set; }
        public string Tittle1 { get; set; }
        public string Tittle2 { get; set; }
        public string LinkContent { get; set; }
        public string LinkAdress { get; set; }
    }
}
